import type { Metadata } from 'next'
import { Great_Vibes, Jost } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'

const vibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-vibes'
})

const jost = Jost({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jost'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`
          ${jost.className}
          ${vibes.variable}
          bg-white dark:bg-black min-h-[100dvh]
          data-[theme='vibes']:font-vibes
          data-[theme='jost']:font-jost
        `}
      >
        <ThemeProvider
          defaultTheme='pink'
          enableColorScheme
          enableSystem
          themes={[
            'pink',
            'light',
            'dark-classic',
            'tangerine',
            'dark-tangerine',
            'mint',
            'dark-mint'
          ]}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
